export interface CountryData {
  code: string          // ISO 2-letter code (e.g., 'BR', 'US', 'ID')
  name: string          // Full country name (e.g., 'Brazil', 'United States')
  symbol: string        // Default token symbol (e.g., 'BRAZIL', 'USA')
  flagEmoji: string     // Flag emoji (e.g., '🇧🇷', '🇺🇸')
  flagUrl: string       // High quality SVG flag CDN URL
  region: 'Americas' | 'Europe' | 'Asia' | 'Africa' | 'Oceania' | 'Middle East'
  description: string   // Default description
  population?: string   // Formatted population for stats
}

export const WORLD_COUNTRIES: CountryData[] = [
  {
    code: 'US',
    name: 'United States',
    symbol: 'USA',
    flagEmoji: '🇺🇸',
    flagUrl: 'https://flagcdn.com/w160/us.png',
    region: 'Americas',
    description: 'Decentralized nation token for the United States on Robinhood Chain.',
    population: '335M',
  },
  {
    code: 'BR',
    name: 'Brazil',
    symbol: 'BRAZIL',
    flagEmoji: '🇧🇷',
    flagUrl: 'https://flagcdn.com/w160/br.png',
    region: 'Americas',
    description: 'Decentralized nation token for Brazil on Robinhood Chain.',
    population: '216M',
  },
  {
    code: 'ID',
    name: 'Indonesia',
    symbol: 'INDONESIA',
    flagEmoji: '🇮🇩',
    flagUrl: 'https://flagcdn.com/w160/id.png',
    region: 'Asia',
    description: 'Decentralized nation token for Indonesia on Robinhood Chain.',
    population: '277M',
  },
  {
    code: 'JP',
    name: 'Japan',
    symbol: 'JAPAN',
    flagEmoji: '🇯🇵',
    flagUrl: 'https://flagcdn.com/w160/jp.png',
    region: 'Asia',
    description: 'Decentralized nation token for Japan on Robinhood Chain.',
    population: '124M',
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    symbol: 'UK',
    flagEmoji: '🇬🇧',
    flagUrl: 'https://flagcdn.com/w160/gb.png',
    region: 'Europe',
    description: 'Decentralized nation token for the United Kingdom on Robinhood Chain.',
    population: '67M',
  },
  {
    code: 'DE',
    name: 'Germany',
    symbol: 'GERMANY',
    flagEmoji: '🇩🇪',
    flagUrl: 'https://flagcdn.com/w160/de.png',
    region: 'Europe',
    description: 'Decentralized nation token for Germany on Robinhood Chain.',
    population: '84M',
  },
  {
    code: 'FR',
    name: 'France',
    symbol: 'FRANCE',
    flagEmoji: '🇫🇷',
    flagUrl: 'https://flagcdn.com/w160/fr.png',
    region: 'Europe',
    description: 'Decentralized nation token for France on Robinhood Chain.',
    population: '68M',
  },
  {
    code: 'KR',
    name: 'South Korea',
    symbol: 'KOREA',
    flagEmoji: '🇰🇷',
    flagUrl: 'https://flagcdn.com/w160/kr.png',
    region: 'Asia',
    description: 'Decentralized nation token for South Korea on Robinhood Chain.',
    population: '51M',
  },
  {
    code: 'CA',
    name: 'Canada',
    symbol: 'CANADA',
    flagEmoji: '🇨🇦',
    flagUrl: 'https://flagcdn.com/w160/ca.png',
    region: 'Americas',
    description: 'Decentralized nation token for Canada on Robinhood Chain.',
    population: '40M',
  },
  {
    code: 'AU',
    name: 'Australia',
    symbol: 'AUSTRALIA',
    flagEmoji: '🇦🇺',
    flagUrl: 'https://flagcdn.com/w160/au.png',
    region: 'Oceania',
    description: 'Decentralized nation token for Australia on Robinhood Chain.',
    population: '26M',
  },
  {
    code: 'IN',
    name: 'India',
    symbol: 'INDIA',
    flagEmoji: '🇮🇳',
    flagUrl: 'https://flagcdn.com/w160/in.png',
    region: 'Asia',
    description: 'Decentralized nation token for India on Robinhood Chain.',
    population: '1.4B',
  },
  {
    code: 'SG',
    name: 'Singapore',
    symbol: 'SINGAPORE',
    flagEmoji: '🇸🇬',
    flagUrl: 'https://flagcdn.com/w160/sg.png',
    region: 'Asia',
    description: 'Decentralized nation token for Singapore on Robinhood Chain.',
    population: '6M',
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    symbol: 'UAE',
    flagEmoji: '🇦🇪',
    flagUrl: 'https://flagcdn.com/w160/ae.png',
    region: 'Middle East',
    description: 'Decentralized nation token for United Arab Emirates on Robinhood Chain.',
    population: '10M',
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    symbol: 'KSA',
    flagEmoji: '🇸🇦',
    flagUrl: 'https://flagcdn.com/w160/sa.png',
    region: 'Middle East',
    description: 'Decentralized nation token for Saudi Arabia on Robinhood Chain.',
    population: '36M',
  },
  {
    code: 'CH',
    name: 'Switzerland',
    symbol: 'SWISS',
    flagEmoji: '🇨🇭',
    flagUrl: 'https://flagcdn.com/w160/ch.png',
    region: 'Europe',
    description: 'Decentralized nation token for Switzerland on Robinhood Chain.',
    population: '9M',
  },
  {
    code: 'IT',
    name: 'Italy',
    symbol: 'ITALY',
    flagEmoji: '🇮🇹',
    flagUrl: 'https://flagcdn.com/w160/it.png',
    region: 'Europe',
    description: 'Decentralized nation token for Italy on Robinhood Chain.',
    population: '59M',
  },
  {
    code: 'ES',
    name: 'Spain',
    symbol: 'SPAIN',
    flagEmoji: '🇪🇸',
    flagUrl: 'https://flagcdn.com/w160/es.png',
    region: 'Europe',
    description: 'Decentralized nation token for Spain on Robinhood Chain.',
    population: '48M',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    symbol: 'HOLLAND',
    flagEmoji: '🇳🇱',
    flagUrl: 'https://flagcdn.com/w160/nl.png',
    region: 'Europe',
    description: 'Decentralized nation token for the Netherlands on Robinhood Chain.',
    population: '18M',
  },
  {
    code: 'TR',
    name: 'Turkey',
    symbol: 'TURKEY',
    flagEmoji: '🇹🇷',
    flagUrl: 'https://flagcdn.com/w160/tr.png',
    region: 'Middle East',
    description: 'Decentralized nation token for Turkey on Robinhood Chain.',
    population: '85M',
  },
  {
    code: 'MX',
    name: 'Mexico',
    symbol: 'MEXICO',
    flagEmoji: '🇲🇽',
    flagUrl: 'https://flagcdn.com/w160/mx.png',
    region: 'Americas',
    description: 'Decentralized nation token for Mexico on Robinhood Chain.',
    population: '128M',
  },
  {
    code: 'AR',
    name: 'Argentina',
    symbol: 'ARGENTINA',
    flagEmoji: '🇦🇷',
    flagUrl: 'https://flagcdn.com/w160/ar.png',
    region: 'Americas',
    description: 'Decentralized nation token for Argentina on Robinhood Chain.',
    population: '46M',
  },
  {
    code: 'VN',
    name: 'Vietnam',
    symbol: 'VIETNAM',
    flagEmoji: '🇻🇳',
    flagUrl: 'https://flagcdn.com/w160/vn.png',
    region: 'Asia',
    description: 'Decentralized nation token for Vietnam on Robinhood Chain.',
    population: '100M',
  },
  {
    code: 'TH',
    name: 'Thailand',
    symbol: 'THAILAND',
    flagEmoji: '🇹🇭',
    flagUrl: 'https://flagcdn.com/w160/th.png',
    region: 'Asia',
    description: 'Decentralized nation token for Thailand on Robinhood Chain.',
    population: '71M',
  },
  {
    code: 'PH',
    name: 'Philippines',
    symbol: 'PHILIPPINES',
    flagEmoji: '🇵🇭',
    flagUrl: 'https://flagcdn.com/w160/ph.png',
    region: 'Asia',
    description: 'Decentralized nation token for Philippines on Robinhood Chain.',
    population: '117M',
  },
  {
    code: 'MY',
    name: 'Malaysia',
    symbol: 'MALAYSIA',
    flagEmoji: '🇲🇾',
    flagUrl: 'https://flagcdn.com/w160/my.png',
    region: 'Asia',
    description: 'Decentralized nation token for Malaysia on Robinhood Chain.',
    population: '34M',
  },
  {
    code: 'NG',
    name: 'Nigeria',
    symbol: 'NIGERIA',
    flagEmoji: '🇳🇬',
    flagUrl: 'https://flagcdn.com/w160/ng.png',
    region: 'Africa',
    description: 'Decentralized nation token for Nigeria on Robinhood Chain.',
    population: '223M',
  },
  {
    code: 'ZA',
    name: 'South Africa',
    symbol: 'SOUTHAFRICA',
    flagEmoji: '🇿🇦',
    flagUrl: 'https://flagcdn.com/w160/za.png',
    region: 'Africa',
    description: 'Decentralized nation token for South Africa on Robinhood Chain.',
    population: '60M',
  },
  {
    code: 'EG',
    name: 'Egypt',
    symbol: 'EGYPT',
    flagEmoji: '🇪🇬',
    flagUrl: 'https://flagcdn.com/w160/eg.png',
    region: 'Africa',
    description: 'Decentralized nation token for Egypt on Robinhood Chain.',
    population: '112M',
  },
  {
    code: 'SE',
    name: 'Sweden',
    symbol: 'SWEDEN',
    flagEmoji: '🇸🇪',
    flagUrl: 'https://flagcdn.com/w160/se.png',
    region: 'Europe',
    description: 'Decentralized nation token for Sweden on Robinhood Chain.',
    population: '10M',
  },
  {
    code: 'NO',
    name: 'Norway',
    symbol: 'NORWAY',
    flagEmoji: '🇳🇴',
    flagUrl: 'https://flagcdn.com/w160/no.png',
    region: 'Europe',
    description: 'Decentralized nation token for Norway on Robinhood Chain.',
    population: '5M',
  },
  {
    code: 'PT',
    name: 'Portugal',
    symbol: 'PORTUGAL',
    flagEmoji: '🇵🇹',
    flagUrl: 'https://flagcdn.com/w160/pt.png',
    region: 'Europe',
    description: 'Decentralized nation token for Portugal on Robinhood Chain.',
    population: '10M',
  },
  {
    code: 'PL',
    name: 'Poland',
    symbol: 'POLAND',
    flagEmoji: '🇵🇱',
    flagUrl: 'https://flagcdn.com/w160/pl.png',
    region: 'Europe',
    description: 'Decentralized nation token for Poland on Robinhood Chain.',
    population: '38M',
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    symbol: 'NZ',
    flagEmoji: '🇳🇿',
    flagUrl: 'https://flagcdn.com/w160/nz.png',
    region: 'Oceania',
    description: 'Decentralized nation token for New Zealand on Robinhood Chain.',
    population: '5M',
  },
  {
    code: 'CL',
    name: 'Chile',
    symbol: 'CHILE',
    flagEmoji: '🇨🇱',
    flagUrl: 'https://flagcdn.com/w160/cl.png',
    region: 'Americas',
    description: 'Decentralized nation token for Chile on Robinhood Chain.',
    population: '19M',
  },
  {
    code: 'CO',
    name: 'Colombia',
    symbol: 'COLOMBIA',
    flagEmoji: '🇨🇴',
    flagUrl: 'https://flagcdn.com/w160/co.png',
    region: 'Americas',
    description: 'Decentralized nation token for Colombia on Robinhood Chain.',
    population: '52M',
  },
]

/**
 * Match an on-chain token with a country by symbol, name, or code
 */
export function matchTokenWithCountry(
  token: { name?: string; symbol?: string; description?: string }
): CountryData | undefined {
  const normSym = (token.symbol || '').toUpperCase().trim()
  const normName = (token.name || '').toLowerCase().trim()

  return WORLD_COUNTRIES.find((c) => {
    return (
      c.symbol.toUpperCase() === normSym ||
      c.code.toUpperCase() === normSym ||
      c.name.toLowerCase() === normName ||
      normName.includes(c.name.toLowerCase())
    )
  })
}
